name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd deviceguard/deviceguard-web
            git fetch origin main
            git reset --hard origin/main
            git clean -fd -e .env -e storage
            corepack enable
            corepack prepare pnpm@latest --activate
            pnpm install
            pnpm store prune
            pnpm migrate:deploy
            pnpm build || exit 1
            pm2 restart deviceguard-web || pm2 start "pnpm start" --name deviceguard-web
            npm cache clean --force
            pnpm store prune
